'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34209
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On


'Original file name:
'Generation date: 2/24/2015 3:55:32 PM
Namespace ServiceReference1.Bing
    '''<summary>
    '''There are no comments for BingSearchContainer in the schema.
    '''</summary>
    Partial Public Class BingSearchContainer
        Inherits Global.System.Data.Services.Client.DataServiceContext
        '''<summary>
        '''Initialize a new BingSearchContainer object.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Sub New(ByVal serviceRoot As Global.System.Uri)
            MyBase.New(serviceRoot)
            Me.ResolveName = AddressOf Me.ResolveNameFromType
            Me.ResolveType = AddressOf Me.ResolveTypeFromName
            Me.OnContextCreated
        End Sub
        Partial Private Sub OnContextCreated()
        End Sub
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private Shared ROOTNAMESPACE As String = GetType(BingSearchContainer).Namespace.Remove(GetType(BingSearchContainer).Namespace.LastIndexOf("ServiceReference1.Bing"))
        '''<summary>
        '''Since the namespace configured for this service reference
        '''in Visual Studio is different from the one indicated in the
        '''server schema, use type-mappers to map between the two.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Protected Function ResolveTypeFromName(ByVal typeName As String) As Global.System.Type
            Dim resolvedType As Global.System.Type = Me.DefaultResolveType(typeName, "Bing", String.Concat(ROOTNAMESPACE, "ServiceReference1.Bing"))
            If (Not (resolvedType) Is Nothing) Then
                Return resolvedType
            End If
            Return Nothing
        End Function
        '''<summary>
        '''Since the namespace configured for this service reference
        '''in Visual Studio is different from the one indicated in the
        '''server schema, use type-mappers to map between the two.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Protected Function ResolveNameFromType(ByVal clientType As Global.System.Type) As String
            If clientType.Namespace.Equals(String.Concat(ROOTNAMESPACE, "ServiceReference1.Bing"), Global.System.StringComparison.OrdinalIgnoreCase) Then
                Return String.Concat("Bing.", clientType.Name)
            End If
            Return Nothing
        End Function
        '''<summary>
        '''There are no comments for ExpandableSearchResultSet in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public ReadOnly Property ExpandableSearchResultSet() As Global.System.Data.Services.Client.DataServiceQuery(Of ExpandableSearchResult)
            Get
                If (Me._ExpandableSearchResultSet Is Nothing) Then
                    Me._ExpandableSearchResultSet = MyBase.CreateQuery(Of ExpandableSearchResult)("ExpandableSearchResultSet")
                End If
                Return Me._ExpandableSearchResultSet
            End Get
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _ExpandableSearchResultSet As Global.System.Data.Services.Client.DataServiceQuery(Of ExpandableSearchResult)
        '''<summary>
        '''There are no comments for WebResultSet in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public ReadOnly Property WebResultSet() As Global.System.Data.Services.Client.DataServiceQuery(Of WebResult)
            Get
                If (Me._WebResultSet Is Nothing) Then
                    Me._WebResultSet = MyBase.CreateQuery(Of WebResult)("WebResultSet")
                End If
                Return Me._WebResultSet
            End Get
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _WebResultSet As Global.System.Data.Services.Client.DataServiceQuery(Of WebResult)
        '''<summary>
        '''There are no comments for ImageResultSet in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public ReadOnly Property ImageResultSet() As Global.System.Data.Services.Client.DataServiceQuery(Of ImageResult)
            Get
                If (Me._ImageResultSet Is Nothing) Then
                    Me._ImageResultSet = MyBase.CreateQuery(Of ImageResult)("ImageResultSet")
                End If
                Return Me._ImageResultSet
            End Get
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _ImageResultSet As Global.System.Data.Services.Client.DataServiceQuery(Of ImageResult)
        '''<summary>
        '''There are no comments for VideoResultSet in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public ReadOnly Property VideoResultSet() As Global.System.Data.Services.Client.DataServiceQuery(Of VideoResult)
            Get
                If (Me._VideoResultSet Is Nothing) Then
                    Me._VideoResultSet = MyBase.CreateQuery(Of VideoResult)("VideoResultSet")
                End If
                Return Me._VideoResultSet
            End Get
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _VideoResultSet As Global.System.Data.Services.Client.DataServiceQuery(Of VideoResult)
        '''<summary>
        '''There are no comments for NewsResultSet in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public ReadOnly Property NewsResultSet() As Global.System.Data.Services.Client.DataServiceQuery(Of NewsResult)
            Get
                If (Me._NewsResultSet Is Nothing) Then
                    Me._NewsResultSet = MyBase.CreateQuery(Of NewsResult)("NewsResultSet")
                End If
                Return Me._NewsResultSet
            End Get
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _NewsResultSet As Global.System.Data.Services.Client.DataServiceQuery(Of NewsResult)
        '''<summary>
        '''There are no comments for RelatedSearchResultSet in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public ReadOnly Property RelatedSearchResultSet() As Global.System.Data.Services.Client.DataServiceQuery(Of RelatedSearchResult)
            Get
                If (Me._RelatedSearchResultSet Is Nothing) Then
                    Me._RelatedSearchResultSet = MyBase.CreateQuery(Of RelatedSearchResult)("RelatedSearchResultSet")
                End If
                Return Me._RelatedSearchResultSet
            End Get
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _RelatedSearchResultSet As Global.System.Data.Services.Client.DataServiceQuery(Of RelatedSearchResult)
        '''<summary>
        '''There are no comments for SpellResultSet in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public ReadOnly Property SpellResultSet() As Global.System.Data.Services.Client.DataServiceQuery(Of SpellResult)
            Get
                If (Me._SpellResultSet Is Nothing) Then
                    Me._SpellResultSet = MyBase.CreateQuery(Of SpellResult)("SpellResultSet")
                End If
                Return Me._SpellResultSet
            End Get
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _SpellResultSet As Global.System.Data.Services.Client.DataServiceQuery(Of SpellResult)
        '''<summary>
        '''There are no comments for ExpandableSearchResultSet in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Sub AddToExpandableSearchResultSet(ByVal expandableSearchResult As ExpandableSearchResult)
            MyBase.AddObject("ExpandableSearchResultSet", expandableSearchResult)
        End Sub
        '''<summary>
        '''There are no comments for WebResultSet in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Sub AddToWebResultSet(ByVal webResult As WebResult)
            MyBase.AddObject("WebResultSet", webResult)
        End Sub
        '''<summary>
        '''There are no comments for ImageResultSet in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Sub AddToImageResultSet(ByVal imageResult As ImageResult)
            MyBase.AddObject("ImageResultSet", imageResult)
        End Sub
        '''<summary>
        '''There are no comments for VideoResultSet in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Sub AddToVideoResultSet(ByVal videoResult As VideoResult)
            MyBase.AddObject("VideoResultSet", videoResult)
        End Sub
        '''<summary>
        '''There are no comments for NewsResultSet in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Sub AddToNewsResultSet(ByVal newsResult As NewsResult)
            MyBase.AddObject("NewsResultSet", newsResult)
        End Sub
        '''<summary>
        '''There are no comments for RelatedSearchResultSet in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Sub AddToRelatedSearchResultSet(ByVal relatedSearchResult As RelatedSearchResult)
            MyBase.AddObject("RelatedSearchResultSet", relatedSearchResult)
        End Sub
        '''<summary>
        '''There are no comments for SpellResultSet in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Sub AddToSpellResultSet(ByVal spellResult As SpellResult)
            MyBase.AddObject("SpellResultSet", spellResult)
        End Sub
    End Class
    '''<summary>
    '''There are no comments for Bing.ExpandableSearchResult in the schema.
    '''</summary>
    '''<KeyProperties>
    '''ID
    '''</KeyProperties>
    <Global.System.Data.Services.Common.EntitySetAttribute("ExpandableSearchResultSet"),  _
     Global.System.Data.Services.Common.DataServiceKeyAttribute("ID")>  _
    Partial Public Class ExpandableSearchResult
        Implements Global.System.ComponentModel.INotifyPropertyChanged
        '''<summary>
        '''Create a new ExpandableSearchResult object.
        '''</summary>
        '''<param name="ID">Initial value of ID.</param>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Shared Function CreateExpandableSearchResult(ByVal ID As Global.System.Guid) As ExpandableSearchResult
            Dim expandableSearchResult As ExpandableSearchResult = New ExpandableSearchResult()
            expandableSearchResult.ID = ID
            Return expandableSearchResult
        End Function
        '''<summary>
        '''There are no comments for Property ID in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property ID() As Global.System.Guid
            Get
                Return Me._ID
            End Get
            Set
                Me.OnIDChanging(value)
                Me._ID = value
                Me.OnIDChanged
                Me.OnPropertyChanged("ID")
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _ID As Global.System.Guid
        Partial Private Sub OnIDChanging(ByVal value As Global.System.Guid)
        End Sub
        Partial Private Sub OnIDChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property WebTotal in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property WebTotal() As Global.System.Nullable(Of Long)
            Get
                Return Me._WebTotal
            End Get
            Set
                Me.OnWebTotalChanging(value)
                Me._WebTotal = value
                Me.OnWebTotalChanged
                Me.OnPropertyChanged("WebTotal")
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _WebTotal As Global.System.Nullable(Of Long)
        Partial Private Sub OnWebTotalChanging(ByVal value As Global.System.Nullable(Of Long))
        End Sub
        Partial Private Sub OnWebTotalChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property WebOffset in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property WebOffset() As Global.System.Nullable(Of Long)
            Get
                Return Me._WebOffset
            End Get
            Set
                Me.OnWebOffsetChanging(value)
                Me._WebOffset = value
                Me.OnWebOffsetChanged
                Me.OnPropertyChanged("WebOffset")
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _WebOffset As Global.System.Nullable(Of Long)
        Partial Private Sub OnWebOffsetChanging(ByVal value As Global.System.Nullable(Of Long))
        End Sub
        Partial Private Sub OnWebOffsetChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property ImageTotal in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property ImageTotal() As Global.System.Nullable(Of Long)
            Get
                Return Me._ImageTotal
            End Get
            Set
                Me.OnImageTotalChanging(value)
                Me._ImageTotal = value
                Me.OnImageTotalChanged
                Me.OnPropertyChanged("ImageTotal")
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _ImageTotal As Global.System.Nullable(Of Long)
        Partial Private Sub OnImageTotalChanging(ByVal value As Global.System.Nullable(Of Long))
        End Sub
        Partial Private Sub OnImageTotalChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property ImageOffset in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property ImageOffset() As Global.System.Nullable(Of Long)
            Get
                Return Me._ImageOffset
            End Get
            Set
                Me.OnImageOffsetChanging(value)
                Me._ImageOffset = value
                Me.OnImageOffsetChanged
                Me.OnPropertyChanged("ImageOffset")
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _ImageOffset As Global.System.Nullable(Of Long)
        Partial Private Sub OnImageOffsetChanging(ByVal value As Global.System.Nullable(Of Long))
        End Sub
        Partial Private Sub OnImageOffsetChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property VideoTotal in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property VideoTotal() As Global.System.Nullable(Of Long)
            Get
                Return Me._VideoTotal
            End Get
            Set
                Me.OnVideoTotalChanging(value)
                Me._VideoTotal = value
                Me.OnVideoTotalChanged
                Me.OnPropertyChanged("VideoTotal")
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _VideoTotal As Global.System.Nullable(Of Long)
        Partial Private Sub OnVideoTotalChanging(ByVal value As Global.System.Nullable(Of Long))
        End Sub
        Partial Private Sub OnVideoTotalChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property VideoOffset in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property VideoOffset() As Global.System.Nullable(Of Long)
            Get
                Return Me._VideoOffset
            End Get
            Set
                Me.OnVideoOffsetChanging(value)
                Me._VideoOffset = value
                Me.OnVideoOffsetChanged
                Me.OnPropertyChanged("VideoOffset")
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _VideoOffset As Global.System.Nullable(Of Long)
        Partial Private Sub OnVideoOffsetChanging(ByVal value As Global.System.Nullable(Of Long))
        End Sub
        Partial Private Sub OnVideoOffsetChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property NewsTotal in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property NewsTotal() As Global.System.Nullable(Of Long)
            Get
                Return Me._NewsTotal
            End Get
            Set
                Me.OnNewsTotalChanging(value)
                Me._NewsTotal = value
                Me.OnNewsTotalChanged
                Me.OnPropertyChanged("NewsTotal")
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _NewsTotal As Global.System.Nullable(Of Long)
        Partial Private Sub OnNewsTotalChanging(ByVal value As Global.System.Nullable(Of Long))
        End Sub
        Partial Private Sub OnNewsTotalChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property NewsOffset in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property NewsOffset() As Global.System.Nullable(Of Long)
            Get
                Return Me._NewsOffset
            End Get
            Set
                Me.OnNewsOffsetChanging(value)
                Me._NewsOffset = value
                Me.OnNewsOffsetChanged
                Me.OnPropertyChanged("NewsOffset")
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _NewsOffset As Global.System.Nullable(Of Long)
        Partial Private Sub OnNewsOffsetChanging(ByVal value As Global.System.Nullable(Of Long))
        End Sub
        Partial Private Sub OnNewsOffsetChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property SpellingSuggestionsTotal in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property SpellingSuggestionsTotal() As Global.System.Nullable(Of Long)
            Get
                Return Me._SpellingSuggestionsTotal
            End Get
            Set
                Me.OnSpellingSuggestionsTotalChanging(value)
                Me._SpellingSuggestionsTotal = value
                Me.OnSpellingSuggestionsTotalChanged
                Me.OnPropertyChanged("SpellingSuggestionsTotal")
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _SpellingSuggestionsTotal As Global.System.Nullable(Of Long)
        Partial Private Sub OnSpellingSuggestionsTotalChanging(ByVal value As Global.System.Nullable(Of Long))
        End Sub
        Partial Private Sub OnSpellingSuggestionsTotalChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property AlteredQuery in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property AlteredQuery() As String
            Get
                Return Me._AlteredQuery
            End Get
            Set
                Me.OnAlteredQueryChanging(value)
                Me._AlteredQuery = value
                Me.OnAlteredQueryChanged
                Me.OnPropertyChanged("AlteredQuery")
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _AlteredQuery As String
        Partial Private Sub OnAlteredQueryChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnAlteredQueryChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property AlterationOverrideQuery in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property AlterationOverrideQuery() As String
            Get
                Return Me._AlterationOverrideQuery
            End Get
            Set
                Me.OnAlterationOverrideQueryChanging(value)
                Me._AlterationOverrideQuery = value
                Me.OnAlterationOverrideQueryChanged
                Me.OnPropertyChanged("AlterationOverrideQuery")
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _AlterationOverrideQuery As String
        Partial Private Sub OnAlterationOverrideQueryChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnAlterationOverrideQueryChanged()
        End Sub
        '''<summary>
        '''There are no comments for Web in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Web() As Global.System.Data.Services.Client.DataServiceCollection(Of WebResult)
            Get
                Return Me._Web
            End Get
            Set
                Me._Web = value
                Me.OnPropertyChanged("Web")
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Web As Global.System.Data.Services.Client.DataServiceCollection(Of WebResult) = New Global.System.Data.Services.Client.DataServiceCollection(Of WebResult)(Nothing, Global.System.Data.Services.Client.TrackingMode.None)
        '''<summary>
        '''There are no comments for Image in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Image() As Global.System.Data.Services.Client.DataServiceCollection(Of ImageResult)
            Get
                Return Me._Image
            End Get
            Set
                Me._Image = value
                Me.OnPropertyChanged("Image")
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Image As Global.System.Data.Services.Client.DataServiceCollection(Of ImageResult) = New Global.System.Data.Services.Client.DataServiceCollection(Of ImageResult)(Nothing, Global.System.Data.Services.Client.TrackingMode.None)
        '''<summary>
        '''There are no comments for Video in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Video() As Global.System.Data.Services.Client.DataServiceCollection(Of VideoResult)
            Get
                Return Me._Video
            End Get
            Set
                Me._Video = value
                Me.OnPropertyChanged("Video")
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Video As Global.System.Data.Services.Client.DataServiceCollection(Of VideoResult) = New Global.System.Data.Services.Client.DataServiceCollection(Of VideoResult)(Nothing, Global.System.Data.Services.Client.TrackingMode.None)
        '''<summary>
        '''There are no comments for News in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property News() As Global.System.Data.Services.Client.DataServiceCollection(Of NewsResult)
            Get
                Return Me._News
            End Get
            Set
                Me._News = value
                Me.OnPropertyChanged("News")
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _News As Global.System.Data.Services.Client.DataServiceCollection(Of NewsResult) = New Global.System.Data.Services.Client.DataServiceCollection(Of NewsResult)(Nothing, Global.System.Data.Services.Client.TrackingMode.None)
        '''<summary>
        '''There are no comments for RelatedSearch in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property RelatedSearch() As Global.System.Data.Services.Client.DataServiceCollection(Of RelatedSearchResult)
            Get
                Return Me._RelatedSearch
            End Get
            Set
                Me._RelatedSearch = value
                Me.OnPropertyChanged("RelatedSearch")
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _RelatedSearch As Global.System.Data.Services.Client.DataServiceCollection(Of RelatedSearchResult) = New Global.System.Data.Services.Client.DataServiceCollection(Of RelatedSearchResult)(Nothing, Global.System.Data.Services.Client.TrackingMode.None)
        '''<summary>
        '''There are no comments for SpellingSuggestions in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property SpellingSuggestions() As Global.System.Data.Services.Client.DataServiceCollection(Of SpellResult)
            Get
                Return Me._SpellingSuggestions
            End Get
            Set
                Me._SpellingSuggestions = value
                Me.OnPropertyChanged("SpellingSuggestions")
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _SpellingSuggestions As Global.System.Data.Services.Client.DataServiceCollection(Of SpellResult) = New Global.System.Data.Services.Client.DataServiceCollection(Of SpellResult)(Nothing, Global.System.Data.Services.Client.TrackingMode.None)
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Event PropertyChanged As Global.System.ComponentModel.PropertyChangedEventHandler Implements Global.System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Protected Overridable Sub OnPropertyChanged(ByVal [property] As String)
            If (Not (Me.PropertyChangedEvent) Is Nothing) Then
                RaiseEvent PropertyChanged(Me, New Global.System.ComponentModel.PropertyChangedEventArgs([property]))
            End If
        End Sub
    End Class
    '''<summary>
    '''There are no comments for Bing.WebResult in the schema.
    '''</summary>
    '''<KeyProperties>
    '''ID
    '''</KeyProperties>
    <Global.System.Data.Services.Common.EntitySetAttribute("WebResultSet"),  _
     Global.System.Data.Services.Common.DataServiceKeyAttribute("ID")>  _
    Partial Public Class WebResult
        Implements Global.System.ComponentModel.INotifyPropertyChanged
        '''<summary>
        '''Create a new WebResult object.
        '''</summary>
        '''<param name="ID">Initial value of ID.</param>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Shared Function CreateWebResult(ByVal ID As Global.System.Guid) As WebResult
            Dim webResult As WebResult = New WebResult()
            webResult.ID = ID
            Return webResult
        End Function
        '''<summary>
        '''There are no comments for Property ID in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property ID() As Global.System.Guid
            Get
                Return Me._ID
            End Get
            Set
                Me.OnIDChanging(value)
                Me._ID = value
                Me.OnIDChanged
                Me.OnPropertyChanged("ID")
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _ID As Global.System.Guid
        Partial Private Sub OnIDChanging(ByVal value As Global.System.Guid)
        End Sub
        Partial Private Sub OnIDChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property Title in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Title() As String
            Get
                Return Me._Title
            End Get
            Set
                Me.OnTitleChanging(value)
                Me._Title = value
                Me.OnTitleChanged
                Me.OnPropertyChanged("Title")
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Title As String
        Partial Private Sub OnTitleChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnTitleChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property Description in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Description() As String
            Get
                Return Me._Description
            End Get
            Set
                Me.OnDescriptionChanging(value)
                Me._Description = value
                Me.OnDescriptionChanged
                Me.OnPropertyChanged("Description")
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Description As String
        Partial Private Sub OnDescriptionChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnDescriptionChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property DisplayUrl in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property DisplayUrl() As String
            Get
                Return Me._DisplayUrl
            End Get
            Set
                Me.OnDisplayUrlChanging(value)
                Me._DisplayUrl = value
                Me.OnDisplayUrlChanged
                Me.OnPropertyChanged("DisplayUrl")
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _DisplayUrl As String
        Partial Private Sub OnDisplayUrlChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnDisplayUrlChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property Url in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Url() As String
            Get
                Return Me._Url
            End Get
            Set
                Me.OnUrlChanging(value)
                Me._Url = value
                Me.OnUrlChanged
                Me.OnPropertyChanged("Url")
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Url As String
        Partial Private Sub OnUrlChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnUrlChanged()
        End Sub
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Event PropertyChanged As Global.System.ComponentModel.PropertyChangedEventHandler Implements Global.System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Protected Overridable Sub OnPropertyChanged(ByVal [property] As String)
            If (Not (Me.PropertyChangedEvent) Is Nothing) Then
                RaiseEvent PropertyChanged(Me, New Global.System.ComponentModel.PropertyChangedEventArgs([property]))
            End If
        End Sub
    End Class
    '''<summary>
    '''There are no comments for ComplexType Bing.Thumbnail in the schema.
    '''</summary>
    Partial Public Class Thumbnail
        Implements Global.System.ComponentModel.INotifyPropertyChanged
        '''<summary>
        '''There are no comments for Property MediaUrl in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property MediaUrl() As String
            Get
                Return Me._MediaUrl
            End Get
            Set
                Me.OnMediaUrlChanging(value)
                Me._MediaUrl = value
                Me.OnMediaUrlChanged
                Me.OnPropertyChanged("MediaUrl")
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _MediaUrl As String
        Partial Private Sub OnMediaUrlChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnMediaUrlChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property ContentType in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property ContentType() As String
            Get
                Return Me._ContentType
            End Get
            Set
                Me.OnContentTypeChanging(value)
                Me._ContentType = value
                Me.OnContentTypeChanged
                Me.OnPropertyChanged("ContentType")
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _ContentType As String
        Partial Private Sub OnContentTypeChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnContentTypeChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property Width in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Width() As Global.System.Nullable(Of Integer)
            Get
                Return Me._Width
            End Get
            Set
                Me.OnWidthChanging(value)
                Me._Width = value
                Me.OnWidthChanged
                Me.OnPropertyChanged("Width")
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Width As Global.System.Nullable(Of Integer)
        Partial Private Sub OnWidthChanging(ByVal value As Global.System.Nullable(Of Integer))
        End Sub
        Partial Private Sub OnWidthChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property Height in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Height() As Global.System.Nullable(Of Integer)
            Get
                Return Me._Height
            End Get
            Set
                Me.OnHeightChanging(value)
                Me._Height = value
                Me.OnHeightChanged
                Me.OnPropertyChanged("Height")
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Height As Global.System.Nullable(Of Integer)
        Partial Private Sub OnHeightChanging(ByVal value As Global.System.Nullable(Of Integer))
        End Sub
        Partial Private Sub OnHeightChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property FileSize in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property FileSize() As Global.System.Nullable(Of Long)
            Get
                Return Me._FileSize
            End Get
            Set
                Me.OnFileSizeChanging(value)
                Me._FileSize = value
                Me.OnFileSizeChanged
                Me.OnPropertyChanged("FileSize")
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _FileSize As Global.System.Nullable(Of Long)
        Partial Private Sub OnFileSizeChanging(ByVal value As Global.System.Nullable(Of Long))
        End Sub
        Partial Private Sub OnFileSizeChanged()
        End Sub
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Event PropertyChanged As Global.System.ComponentModel.PropertyChangedEventHandler Implements Global.System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Protected Overridable Sub OnPropertyChanged(ByVal [property] As String)
            If (Not (Me.PropertyChangedEvent) Is Nothing) Then
                RaiseEvent PropertyChanged(Me, New Global.System.ComponentModel.PropertyChangedEventArgs([property]))
            End If
        End Sub
    End Class
    '''<summary>
    '''There are no comments for Bing.ImageResult in the schema.
    '''</summary>
    '''<KeyProperties>
    '''ID
    '''</KeyProperties>
    <Global.System.Data.Services.Common.EntitySetAttribute("ImageResultSet"),  _
     Global.System.Data.Services.Common.DataServiceKeyAttribute("ID")>  _
    Partial Public Class ImageResult
        Implements Global.System.ComponentModel.INotifyPropertyChanged
        '''<summary>
        '''Create a new ImageResult object.
        '''</summary>
        '''<param name="ID">Initial value of ID.</param>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Shared Function CreateImageResult(ByVal ID As Global.System.Guid) As ImageResult
            Dim imageResult As ImageResult = New ImageResult()
            imageResult.ID = ID
            Return imageResult
        End Function
        '''<summary>
        '''There are no comments for Property ID in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property ID() As Global.System.Guid
            Get
                Return Me._ID
            End Get
            Set
                Me.OnIDChanging(value)
                Me._ID = value
                Me.OnIDChanged
                Me.OnPropertyChanged("ID")
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _ID As Global.System.Guid
        Partial Private Sub OnIDChanging(ByVal value As Global.System.Guid)
        End Sub
        Partial Private Sub OnIDChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property Title in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Title() As String
            Get
                Return Me._Title
            End Get
            Set
                Me.OnTitleChanging(value)
                Me._Title = value
                Me.OnTitleChanged
                Me.OnPropertyChanged("Title")
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Title As String
        Partial Private Sub OnTitleChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnTitleChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property MediaUrl in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property MediaUrl() As String
            Get
                Return Me._MediaUrl
            End Get
            Set
                Me.OnMediaUrlChanging(value)
                Me._MediaUrl = value
                Me.OnMediaUrlChanged
                Me.OnPropertyChanged("MediaUrl")
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _MediaUrl As String
        Partial Private Sub OnMediaUrlChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnMediaUrlChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property SourceUrl in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property SourceUrl() As String
            Get
                Return Me._SourceUrl
            End Get
            Set
                Me.OnSourceUrlChanging(value)
                Me._SourceUrl = value
                Me.OnSourceUrlChanged
                Me.OnPropertyChanged("SourceUrl")
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _SourceUrl As String
        Partial Private Sub OnSourceUrlChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnSourceUrlChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property DisplayUrl in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property DisplayUrl() As String
            Get
                Return Me._DisplayUrl
            End Get
            Set
                Me.OnDisplayUrlChanging(value)
                Me._DisplayUrl = value
                Me.OnDisplayUrlChanged
                Me.OnPropertyChanged("DisplayUrl")
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _DisplayUrl As String
        Partial Private Sub OnDisplayUrlChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnDisplayUrlChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property Width in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Width() As Global.System.Nullable(Of Integer)
            Get
                Return Me._Width
            End Get
            Set
                Me.OnWidthChanging(value)
                Me._Width = value
                Me.OnWidthChanged
                Me.OnPropertyChanged("Width")
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Width As Global.System.Nullable(Of Integer)
        Partial Private Sub OnWidthChanging(ByVal value As Global.System.Nullable(Of Integer))
        End Sub
        Partial Private Sub OnWidthChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property Height in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Height() As Global.System.Nullable(Of Integer)
            Get
                Return Me._Height
            End Get
            Set
                Me.OnHeightChanging(value)
                Me._Height = value
                Me.OnHeightChanged
                Me.OnPropertyChanged("Height")
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Height As Global.System.Nullable(Of Integer)
        Partial Private Sub OnHeightChanging(ByVal value As Global.System.Nullable(Of Integer))
        End Sub
        Partial Private Sub OnHeightChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property FileSize in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property FileSize() As Global.System.Nullable(Of Long)
            Get
                Return Me._FileSize
            End Get
            Set
                Me.OnFileSizeChanging(value)
                Me._FileSize = value
                Me.OnFileSizeChanged
                Me.OnPropertyChanged("FileSize")
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _FileSize As Global.System.Nullable(Of Long)
        Partial Private Sub OnFileSizeChanging(ByVal value As Global.System.Nullable(Of Long))
        End Sub
        Partial Private Sub OnFileSizeChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property ContentType in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property ContentType() As String
            Get
                Return Me._ContentType
            End Get
            Set
                Me.OnContentTypeChanging(value)
                Me._ContentType = value
                Me.OnContentTypeChanged
                Me.OnPropertyChanged("ContentType")
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _ContentType As String
        Partial Private Sub OnContentTypeChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnContentTypeChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property Thumbnail in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Thumbnail() As Thumbnail
            Get
                If ((Me._Thumbnail Is Nothing)  _
                            AndAlso (Me._ThumbnailInitialized <> true)) Then
                    Me._Thumbnail = New Thumbnail()
                    Me._ThumbnailInitialized = true
                End If
                Return Me._Thumbnail
            End Get
            Set
                Me.OnThumbnailChanging(value)
                Me._Thumbnail = value
                Me._ThumbnailInitialized = true
                Me.OnThumbnailChanged
                Me.OnPropertyChanged("Thumbnail")
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Thumbnail As Thumbnail
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _ThumbnailInitialized As Boolean
        Partial Private Sub OnThumbnailChanging(ByVal value As Thumbnail)
        End Sub
        Partial Private Sub OnThumbnailChanged()
        End Sub
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Event PropertyChanged As Global.System.ComponentModel.PropertyChangedEventHandler Implements Global.System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Protected Overridable Sub OnPropertyChanged(ByVal [property] As String)
            If (Not (Me.PropertyChangedEvent) Is Nothing) Then
                RaiseEvent PropertyChanged(Me, New Global.System.ComponentModel.PropertyChangedEventArgs([property]))
            End If
        End Sub
    End Class
    '''<summary>
    '''There are no comments for Bing.VideoResult in the schema.
    '''</summary>
    '''<KeyProperties>
    '''ID
    '''</KeyProperties>
    <Global.System.Data.Services.Common.EntitySetAttribute("VideoResultSet"),  _
     Global.System.Data.Services.Common.DataServiceKeyAttribute("ID")>  _
    Partial Public Class VideoResult
        Implements Global.System.ComponentModel.INotifyPropertyChanged
        '''<summary>
        '''Create a new VideoResult object.
        '''</summary>
        '''<param name="ID">Initial value of ID.</param>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Shared Function CreateVideoResult(ByVal ID As Global.System.Guid) As VideoResult
            Dim videoResult As VideoResult = New VideoResult()
            videoResult.ID = ID
            Return videoResult
        End Function
        '''<summary>
        '''There are no comments for Property ID in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property ID() As Global.System.Guid
            Get
                Return Me._ID
            End Get
            Set
                Me.OnIDChanging(value)
                Me._ID = value
                Me.OnIDChanged
                Me.OnPropertyChanged("ID")
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _ID As Global.System.Guid
        Partial Private Sub OnIDChanging(ByVal value As Global.System.Guid)
        End Sub
        Partial Private Sub OnIDChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property Title in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Title() As String
            Get
                Return Me._Title
            End Get
            Set
                Me.OnTitleChanging(value)
                Me._Title = value
                Me.OnTitleChanged
                Me.OnPropertyChanged("Title")
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Title As String
        Partial Private Sub OnTitleChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnTitleChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property MediaUrl in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property MediaUrl() As String
            Get
                Return Me._MediaUrl
            End Get
            Set
                Me.OnMediaUrlChanging(value)
                Me._MediaUrl = value
                Me.OnMediaUrlChanged
                Me.OnPropertyChanged("MediaUrl")
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _MediaUrl As String
        Partial Private Sub OnMediaUrlChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnMediaUrlChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property DisplayUrl in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property DisplayUrl() As String
            Get
                Return Me._DisplayUrl
            End Get
            Set
                Me.OnDisplayUrlChanging(value)
                Me._DisplayUrl = value
                Me.OnDisplayUrlChanged
                Me.OnPropertyChanged("DisplayUrl")
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _DisplayUrl As String
        Partial Private Sub OnDisplayUrlChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnDisplayUrlChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property RunTime in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property RunTime() As Global.System.Nullable(Of Integer)
            Get
                Return Me._RunTime
            End Get
            Set
                Me.OnRunTimeChanging(value)
                Me._RunTime = value
                Me.OnRunTimeChanged
                Me.OnPropertyChanged("RunTime")
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _RunTime As Global.System.Nullable(Of Integer)
        Partial Private Sub OnRunTimeChanging(ByVal value As Global.System.Nullable(Of Integer))
        End Sub
        Partial Private Sub OnRunTimeChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property Thumbnail in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Thumbnail() As Thumbnail
            Get
                If ((Me._Thumbnail Is Nothing)  _
                            AndAlso (Me._ThumbnailInitialized <> true)) Then
                    Me._Thumbnail = New Thumbnail()
                    Me._ThumbnailInitialized = true
                End If
                Return Me._Thumbnail
            End Get
            Set
                Me.OnThumbnailChanging(value)
                Me._Thumbnail = value
                Me._ThumbnailInitialized = true
                Me.OnThumbnailChanged
                Me.OnPropertyChanged("Thumbnail")
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Thumbnail As Thumbnail
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _ThumbnailInitialized As Boolean
        Partial Private Sub OnThumbnailChanging(ByVal value As Thumbnail)
        End Sub
        Partial Private Sub OnThumbnailChanged()
        End Sub
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Event PropertyChanged As Global.System.ComponentModel.PropertyChangedEventHandler Implements Global.System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Protected Overridable Sub OnPropertyChanged(ByVal [property] As String)
            If (Not (Me.PropertyChangedEvent) Is Nothing) Then
                RaiseEvent PropertyChanged(Me, New Global.System.ComponentModel.PropertyChangedEventArgs([property]))
            End If
        End Sub
    End Class
    '''<summary>
    '''There are no comments for Bing.NewsResult in the schema.
    '''</summary>
    '''<KeyProperties>
    '''ID
    '''</KeyProperties>
    <Global.System.Data.Services.Common.EntitySetAttribute("NewsResultSet"),  _
     Global.System.Data.Services.Common.DataServiceKeyAttribute("ID")>  _
    Partial Public Class NewsResult
        Implements Global.System.ComponentModel.INotifyPropertyChanged
        '''<summary>
        '''Create a new NewsResult object.
        '''</summary>
        '''<param name="ID">Initial value of ID.</param>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Shared Function CreateNewsResult(ByVal ID As Global.System.Guid) As NewsResult
            Dim newsResult As NewsResult = New NewsResult()
            newsResult.ID = ID
            Return newsResult
        End Function
        '''<summary>
        '''There are no comments for Property ID in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property ID() As Global.System.Guid
            Get
                Return Me._ID
            End Get
            Set
                Me.OnIDChanging(value)
                Me._ID = value
                Me.OnIDChanged
                Me.OnPropertyChanged("ID")
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _ID As Global.System.Guid
        Partial Private Sub OnIDChanging(ByVal value As Global.System.Guid)
        End Sub
        Partial Private Sub OnIDChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property Title in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Title() As String
            Get
                Return Me._Title
            End Get
            Set
                Me.OnTitleChanging(value)
                Me._Title = value
                Me.OnTitleChanged
                Me.OnPropertyChanged("Title")
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Title As String
        Partial Private Sub OnTitleChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnTitleChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property Url in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Url() As String
            Get
                Return Me._Url
            End Get
            Set
                Me.OnUrlChanging(value)
                Me._Url = value
                Me.OnUrlChanged
                Me.OnPropertyChanged("Url")
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Url As String
        Partial Private Sub OnUrlChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnUrlChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property Source in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Source() As String
            Get
                Return Me._Source
            End Get
            Set
                Me.OnSourceChanging(value)
                Me._Source = value
                Me.OnSourceChanged
                Me.OnPropertyChanged("Source")
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Source As String
        Partial Private Sub OnSourceChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnSourceChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property Description in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Description() As String
            Get
                Return Me._Description
            End Get
            Set
                Me.OnDescriptionChanging(value)
                Me._Description = value
                Me.OnDescriptionChanged
                Me.OnPropertyChanged("Description")
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Description As String
        Partial Private Sub OnDescriptionChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnDescriptionChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property Date in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property [Date]() As Global.System.Nullable(Of Date)
            Get
                Return Me._Date
            End Get
            Set
                Me.OnDateChanging(value)
                Me._Date = value
                Me.OnDateChanged
                Me.OnPropertyChanged("Date")
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Date As Global.System.Nullable(Of Date)
        Partial Private Sub OnDateChanging(ByVal value As Global.System.Nullable(Of Date))
        End Sub
        Partial Private Sub OnDateChanged()
        End Sub
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Event PropertyChanged As Global.System.ComponentModel.PropertyChangedEventHandler Implements Global.System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Protected Overridable Sub OnPropertyChanged(ByVal [property] As String)
            If (Not (Me.PropertyChangedEvent) Is Nothing) Then
                RaiseEvent PropertyChanged(Me, New Global.System.ComponentModel.PropertyChangedEventArgs([property]))
            End If
        End Sub
    End Class
    '''<summary>
    '''There are no comments for Bing.RelatedSearchResult in the schema.
    '''</summary>
    '''<KeyProperties>
    '''ID
    '''</KeyProperties>
    <Global.System.Data.Services.Common.EntitySetAttribute("RelatedSearchResultSet"),  _
     Global.System.Data.Services.Common.DataServiceKeyAttribute("ID")>  _
    Partial Public Class RelatedSearchResult
        Implements Global.System.ComponentModel.INotifyPropertyChanged
        '''<summary>
        '''Create a new RelatedSearchResult object.
        '''</summary>
        '''<param name="ID">Initial value of ID.</param>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Shared Function CreateRelatedSearchResult(ByVal ID As Global.System.Guid) As RelatedSearchResult
            Dim relatedSearchResult As RelatedSearchResult = New RelatedSearchResult()
            relatedSearchResult.ID = ID
            Return relatedSearchResult
        End Function
        '''<summary>
        '''There are no comments for Property ID in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property ID() As Global.System.Guid
            Get
                Return Me._ID
            End Get
            Set
                Me.OnIDChanging(value)
                Me._ID = value
                Me.OnIDChanged
                Me.OnPropertyChanged("ID")
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _ID As Global.System.Guid
        Partial Private Sub OnIDChanging(ByVal value As Global.System.Guid)
        End Sub
        Partial Private Sub OnIDChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property Title in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Title() As String
            Get
                Return Me._Title
            End Get
            Set
                Me.OnTitleChanging(value)
                Me._Title = value
                Me.OnTitleChanged
                Me.OnPropertyChanged("Title")
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Title As String
        Partial Private Sub OnTitleChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnTitleChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property BingUrl in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property BingUrl() As String
            Get
                Return Me._BingUrl
            End Get
            Set
                Me.OnBingUrlChanging(value)
                Me._BingUrl = value
                Me.OnBingUrlChanged
                Me.OnPropertyChanged("BingUrl")
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _BingUrl As String
        Partial Private Sub OnBingUrlChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnBingUrlChanged()
        End Sub
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Event PropertyChanged As Global.System.ComponentModel.PropertyChangedEventHandler Implements Global.System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Protected Overridable Sub OnPropertyChanged(ByVal [property] As String)
            If (Not (Me.PropertyChangedEvent) Is Nothing) Then
                RaiseEvent PropertyChanged(Me, New Global.System.ComponentModel.PropertyChangedEventArgs([property]))
            End If
        End Sub
    End Class
    '''<summary>
    '''There are no comments for Bing.SpellResult in the schema.
    '''</summary>
    '''<KeyProperties>
    '''ID
    '''</KeyProperties>
    <Global.System.Data.Services.Common.EntitySetAttribute("SpellResultSet"),  _
     Global.System.Data.Services.Common.DataServiceKeyAttribute("ID")>  _
    Partial Public Class SpellResult
        Implements Global.System.ComponentModel.INotifyPropertyChanged
        '''<summary>
        '''Create a new SpellResult object.
        '''</summary>
        '''<param name="ID">Initial value of ID.</param>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Shared Function CreateSpellResult(ByVal ID As Global.System.Guid) As SpellResult
            Dim spellResult As SpellResult = New SpellResult()
            spellResult.ID = ID
            Return spellResult
        End Function
        '''<summary>
        '''There are no comments for Property ID in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property ID() As Global.System.Guid
            Get
                Return Me._ID
            End Get
            Set
                Me.OnIDChanging(value)
                Me._ID = value
                Me.OnIDChanged
                Me.OnPropertyChanged("ID")
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _ID As Global.System.Guid
        Partial Private Sub OnIDChanging(ByVal value As Global.System.Guid)
        End Sub
        Partial Private Sub OnIDChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property Value in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Value() As String
            Get
                Return Me._Value
            End Get
            Set
                Me.OnValueChanging(value)
                Me._Value = value
                Me.OnValueChanged
                Me.OnPropertyChanged("Value")
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Value As String
        Partial Private Sub OnValueChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnValueChanged()
        End Sub
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Event PropertyChanged As Global.System.ComponentModel.PropertyChangedEventHandler Implements Global.System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Protected Overridable Sub OnPropertyChanged(ByVal [property] As String)
            If (Not (Me.PropertyChangedEvent) Is Nothing) Then
                RaiseEvent PropertyChanged(Me, New Global.System.ComponentModel.PropertyChangedEventArgs([property]))
            End If
        End Sub
    End Class
End Namespace
